//go:build e2e

package e2e

import (
	"testing"
	"time"
)

func TestBlackBox(t *testing.T) {
	binary := buildApp(t)

	t.Run("starts and quits through a real terminal", func(t *testing.T) {
		app := startApp(t, binary, t.TempDir())
		app.waitFor(t, "[ Apps ]", 10*time.Second)
		app.send(t, "q")
		app.wait(t)
	})

	fixture := installBrewFixture(t)
	t.Run("uninstalls a real cask", func(t *testing.T) {
		app := startApp(t, binary, fixture.home)
		app.waitFor(t, "casks installed", 20*time.Second)
		at := app.mark()
		app.send(t, "/"+fixture.cask+"\r")
		app.waitForAfter(t, at, "Search: "+fixture.cask+" · 1 of", 20*time.Second)
		at = app.mark()
		app.send(t, "d")
		app.waitForAfter(t, at, "Uninstall "+fixture.cask+"?", 10*time.Second)
		app.send(t, "y")
		app.waitForAfter(t, at, "Uninstalled "+fixture.cask, 30*time.Second)
		app.send(t, "q")
		app.wait(t)
		fixture.requireCaskNotInstalled(t)
	})

	t.Run("finds a real formula and cancels its uninstall", func(t *testing.T) {
		app := startApp(t, binary, fixture.home)
		app.waitFor(t, "casks installed", 20*time.Second)
		at := app.mark()
		app.send(t, "\t")
		app.waitForAfter(t, at, "formulae installed", 20*time.Second)
		at = app.mark()
		app.send(t, "/"+fixture.root+"\r")
		app.waitForAfter(t, at, "Search: "+fixture.root+" · 1 of", 20*time.Second)
		at = app.mark()
		app.send(t, "d")
		app.waitForAfter(t, at, "Uninstall "+fixture.root+"?", 10*time.Second)
		app.send(t, "n")
		app.waitForAfter(t, at, "Uninstall cancelled", 10*time.Second)
		app.send(t, "q")
		app.wait(t)
		fixture.requireInstalled(t, fixture.root, "1.0")
	})

	fixture.setRootVersion(t, "2.0")
	fixture.requireOutdated(t)
	t.Run("upgrades a real outdated formula", func(t *testing.T) {
		app := startApp(t, binary, fixture.home)
		app.waitFor(t, "casks installed", 20*time.Second)
		at := app.mark()
		app.send(t, "\t")
		app.waitForAfter(t, at, "formulae installed", 20*time.Second)
		at = app.mark()
		app.send(t, "/"+fixture.root+"\r")
		app.waitForAfter(t, at, "Search: "+fixture.root+" · 1 of", 20*time.Second)
		at = app.mark()
		app.send(t, "u")
		app.waitForAfter(t, at, "Upgrade "+fixture.root+"?", 10*time.Second)
		app.send(t, "y")
		app.waitForAfter(t, at, "Upgraded "+fixture.root, 30*time.Second)
		app.send(t, "q")
		app.wait(t)
		fixture.requireInstalled(t, fixture.root, "2.0")
	})

	fixture.requireDependency(t)
	t.Run("reveals a real dependency", func(t *testing.T) {
		app := startApp(t, binary, fixture.home)
		app.waitFor(t, "casks installed", 20*time.Second)
		at := app.mark()
		app.send(t, "\t")
		app.waitForAfter(t, at, "formulae installed", 20*time.Second)
		at = app.mark()
		app.send(t, "a")
		app.waitForAfter(t, at, "Dependencies: shown", 10*time.Second)
		at = app.mark()
		app.send(t, "/")
		app.waitForAfter(t, at, "Search: is:dep_", 10*time.Second)
		at = app.mark()
		app.send(t, " "+fixture.dep)
		app.waitForAfter(t, at, fixture.dep+"_", 20*time.Second)
		app.send(t, "\r")
		app.waitForAfter(t, at, "lazybrew black-box fixture", 20*time.Second)
		at = app.mark()
		app.send(t, "d")
		app.waitForAfter(t, at, "Uninstall "+fixture.dep+"?", 10*time.Second)
		app.send(t, "n")
		app.waitForAfter(t, at, "Uninstall cancelled", 10*time.Second)
		app.send(t, "q")
		app.wait(t)
		fixture.requireInstalled(t, fixture.dep, "1.0")
	})

	fixture.cleanupOldRoot(t)
	t.Run("uninstalls a real formula", func(t *testing.T) {
		app := startApp(t, binary, fixture.home)
		app.waitFor(t, "casks installed", 20*time.Second)
		at := app.mark()
		app.send(t, "\t")
		app.waitForAfter(t, at, "formulae installed", 20*time.Second)
		at = app.mark()
		app.send(t, "/"+fixture.root+"\r")
		app.waitForAfter(t, at, "Search: "+fixture.root+" · 1 of", 20*time.Second)
		at = app.mark()
		app.send(t, "d")
		app.waitForAfter(t, at, "Uninstall "+fixture.root+"?", 10*time.Second)
		app.send(t, "y")
		app.waitForAfter(t, at, "Uninstalled "+fixture.root, 30*time.Second)
		app.send(t, "q")
		app.wait(t)
		fixture.requireNotInstalled(t, fixture.root)
	})
}
